### ISSUE TITLE
Image upload: internal server error / out of memory error

### ISSUE THREAD

**Issue by weddingdj** [IdeaSpaceVR/IdeaSpace#27]
Intervention image causes an out of memory error when large images are being resized.

**Comment by SteveX** [comment]
Running IdeaSpace on AMPPS locally I get an internal server error when uploading an image, even a very small image.

This is in the log:
[2016-07-07 11:24:55] local.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /Applications/AMPPS/www/idea.space/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67

**Comment by chriscar** [comment]
The TokenMismatchException happens when there is a different between the token generated and embedded in the page and the token on the server side. I am not an expert on AMPPS but I bet it has something to do with the session configuration in your setup. I tested IdeaSpace with MAMP and it worked out of the box.

**Comment by chriscar** [comment]
This could be helpful for you: http://chilion.nl/configure-ampps-for-laravel/

**Comment by qwani** [comment]
![default](https://cloud.githubusercontent.com/assets/23303973/20081454/cd2e9864-a560-11e6-90f0-8a9413d5cb42.png)
after upping the size of panorama image to 20 mb but kept the post size at 8 mb i uploaded an almost 3 mb image and it gave me the internal server error

**Comment by chriscar** [comment]
@qwani did you get an out of memory error in storage/logs/laravel.log? It can happen on shared hosts if there is not enough memory available for php. I hope I can address this memory error better in the upcoming release. Any ideas are welcome!

**Comment by qwani** [comment]
yes it was as you said and the server admin fixed it, i will share his souloution when he reply back to my email thank you for this good software, 
when will we be able to add 360 videos ?

**Comment by chriscar** [comment]
Great, you could post the solution on https://forum.ideaspacevr.org
I am working on the v1.0.0 release which includes 360 videos. Hope to have it ready soon!

**Comment by qwani** [comment]
sure ill post it to github page wish all good luck

On 11/12/16, Chris <notifications@github.com> wrote:
> Great, you could post the solution on https://forum.ideaspacevr.org
> I am working on the v1.0.0 release which includes 360 videos. Hope to have
> it ready soon!
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/IdeaSpaceVR/IdeaSpace/issues/27#issuecomment-260080062


-- 
po.box 2668
zip code :71461
