### ISSUE TITLE
Preview not working on XAMPP on Windows

### ISSUE THREAD

**Issue by mkopar** [IdeaSpaceVR/IdeaSpace#46]
I tried to create space with IdeaSpaceVR and on preview got:

![image](https://cloud.githubusercontent.com/assets/5441778/26760787/b36648cc-4921-11e7-8c8a-39137b332160.png)

I think the issue lies here:

![image](https://cloud.githubusercontent.com/assets/5441778/26760794/d268414e-4921-11e7-92b9-3724108b7b9e.png)

but unfortunately I don't know how to fix this issue.

**Comment by weddingdj** [comment]
On the first screenshot there is an unknown character in the path, after /themes. Please verify that the path and directory name /themes/vr-view-360-image is correct in your IdeaSpaceVR installation. 

The second screenshot just says that some themes are active and others are not, depending if you activated them on the Themes page in the web interface.

**Comment by mkopar** [comment]
I know it's unknown character in the path, but I think that is because of the backslash character in the isvr_themes table:

![image](https://cloud.githubusercontent.com/assets/5441778/26781411/9f91977a-49ee-11e7-9a1f-fd46aaff4db5.png)

If I change 'themes\vr-view-360-image' to 'themes/vr-view-360-image' by hand in the database the preview starts working, but after that application stops working when I wanted to edit the space.

**Comment by weddingdj** [comment]
I see. I fixed it in master. This line should fix your issue:

https://github.com/IdeaSpaceVR/IdeaSpace/blob/master/app/Http/Controllers/Admin/ThemesController.php#L49

Please let me know.

**Comment by weddingdj** [comment]
You also have to delete the contents of the table isvr_themes, then go to the Themes admin page in the web interface again and the tables will be filled with themes/<theme name>.
