### ISSUE TITLE
IdeaSpace 360 Photo Tour - navigation to spheres not working

### ISSUE THREAD

**Issue by nafem** [IdeaSpaceVR/IdeaSpace#49]
It is possible to create a navigation hotspot to another sphere but they don't appear in the viewer. And when edited they cause an error:

VM1862:1 Uncaught SyntaxError: Unexpected token ] in JSON at position 0

Which I think is emanating from: at HTMLDivElement.<anonymous> (field_position_add_edit.js:87)

IdeaSpace 1.0.4
Photo Tour 1.1
Chrome 62

**Comment by weddingdj** [comment]
Which IdeaSpaceVR version are you using? 
Which Photo Tour version are you using?
Where does the error occur? - When setting the navigation hotspot or in the viewer?

**Comment by nafem** [comment]
Updated original post with versions

**Comment by weddingdj** [comment]
It could be that there is something wrong with the IdeaSpaceVR installation path... is there an index.php in your path?

**Comment by nafem** [comment]
I have the mod_rewrite working correctly so index.php is not in the path.

I just created a separate Space using the same image and same links and it works fine, but the previous version is still creating errors. I will do some further testing and close if I can't reproduce the error again.

**Comment by nafem** [comment]
It seems it was a one off. Closing
