### ISSUE TITLE
Photosphere 'Thumb' in Spheres list

### ISSUE THREAD

**Issue by PatBloom** [IdeaSpaceVR/IdeaSpace#54]
A nice addition to the spheres overview list would be a thumb (maybe on rollover) of the sphere. I currently have a walkthough with over 30 spheres (and still adding some) but it would be nice to have some visual feedback - would make the workflow much faster.

**Comment by weddingdj** [comment]
Are you talking about the photo sphere select box when you position the navigation hotspots?

**Comment by PatBloom** [comment]
No in the listing of spheres in the "Edit Space".

![screen shot 159](https://user-images.githubusercontent.com/35543396/36119259-b642c5ee-103f-11e8-96b0-1635f92f63b5.png)

**Comment by weddingdj** [comment]
I see. There could be a config parameter in the config.php file for a theme which would allow to specify a preview image, or no preview image.

**Comment by PatBloom** [comment]
Yeh (sorry for the late response) but it could also be main functionality as it shouldn't be consuming that much resources. It would at least make it more intuitive to use.

**Comment by weddingdj** [comment]
The reason for making it configurable in config.php is, because there can be content types with no images or photo spheres, but just 3D models or text fields etc.

**Comment by weddingdj** [comment]
@PatBloom In the next release 
![screen shot 2018-04-12 at 23 03 03](https://user-images.githubusercontent.com/3025886/38714776-cffd4d26-3ea5-11e8-9477-8e0f7711ccc4.png)
