### ISSUE TITLE
Using Controller in 360 Photo Tour

### ISSUE THREAD

**Issue by GarvitArya** [IdeaSpaceVR/IdeaSpace#57]
I am trying to use bloutooth controller for android to navigate in VR for hotspots. But controllers are not working. I have tried on different browsers( with gamepad flag enabled) and mobile devices
Is there something I am missing out?

**Comment by weddingdj** [comment]
Are you using a Google Daydream VR controller?

**Comment by GarvitArya** [comment]
No my mobile is not daydream compatible, want to navigate in google cardboard and hence using controller like [https://www.amazon.in/Bluetooth-Controller-Gamepad-Cardboard-discount/dp/B078KKBQKZ?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=7c6d3587-60ea-4ee8-8e41-358b127a1e58](url)

**Comment by weddingdj** [comment]
I am sure it could be achieved but you have to look at A-Frame and how to implement it.
