### ISSUE TITLE
Register page shows an error

### ISSUE THREAD

**Issue by GarvitArya** [IdeaSpaceVR/IdeaSpace#60]
I want to enable multiple registrations but when I try to hit "/register" url, it gives the following error:

[
![screen shot 2018-07-31 at 9 45 06 pm](https://user-images.githubusercontent.com/10580694/43472672-adc62f86-950b-11e8-91ef-29327f80a1b1.png)
](url)

**Comment by weddingdj** [comment]
User Registration / multiple users is not implemented in the current version.
