### ISSUE TITLE
Installing IdeaSpaceVR (VRStoryGram SWAG Incentive)

### ISSUE THREAD

**Issue by hnstone** [IdeaSpaceVR/IdeaSpace#62]
I would really appreciate any assistance with this!!!! I can send some VRStoryGram for the person/s who help me get this working!!! in addition to your chance for swag from Mozilla!!

I am looking for help installing IdeaSpaceVR for my Mozz Fest Project. I have completed setting up the server and have downloaded the software and then unzipped and put it in the the correct directory. I am following: https://www.ideaspacevr.org/documentation/1.1#installing-ideaspace
and am on step 4.

I am installing hosting my website and IdeaSpaceVR on the same server. I created a /vr directory
From the command line I can see
/var/www/html/vr and in there are all of the IdeaSpaceVR assets. However, when I go to my https://myipaddress/vr I get a 404 error.

I followed the attached directions:

https://forum.ideaspacevr.org/topic/11/404-not-found-error-during-installation

and added

<Directory /var/www/html>
AllowOverride All
Order allow,deny
allow from all

as well as

<Directory /var/www/html/vr>
AllowOverride All

but it did not help. As I previously mentioned there is SWAG from VRStoryGram for the person/s who help me get this working!!!

**Comment by weddingdj** [comment]
Does the .htaccess file exist? https://github.com/IdeaSpaceVR/IdeaSpace/blob/master/.htaccess

**Comment by weddingdj** [comment]
I guess you installed php on your server and the apache2 mod_rewrite module is installed and enabled, right? Could you test and put a simple test.php file into your /var/www/html/var directory and open it in your web browser: https://myipaddress/vr/test.php Does this give you an error?

**Comment by weddingdj** [comment]
Remove the following lines from you .htaccess file for now:

<Directory /var/www/html>
AllowOverride All
Order allow,deny
allow from all

<Directory /var/www/html/vr>
AllowOverride All

**Comment by hnstone** [comment]
Ok. Doing that now

**Comment by hnstone** [comment]
Somehow the .htaccess file disappeared.

**Comment by hnstone** [comment]
I found it

**Comment by hnstone** [comment]
Ok. I deleted it

**Comment by hnstone** [comment]
I still cannot connect to the dB
