### ISSUE TITLE
photosphere

### ISSUE THREAD

**Issue by konstantinosko** [IdeaSpaceVR/IdeaSpace#67]
I am trying to create a photosphere 360 tour, but all my images are distorted after i upload them on the photosphere, my main guess is that the problem is that my images aren't 2:1 aspect ratio.
Is there a way to ensure the photos i take will end up being 2:1 ratio by taking the photos from an android phone ? 
An answer would really help !!!

**Comment by weddingdj** [comment]
I used an Android app to create 360 photos which were in 2:1 format. Which app are you using?

**Comment by konstantinosko** [comment]
Google carboard camera and my default camera apk which it has panorama360 mode... Any other apk?

**Comment by weddingdj** [comment]
I used the same I think. The 360 panorama created a 2:1 format for me. What is the image resolution of your images?

**Comment by konstantinosko** [comment]
Arround 6674 x 1057

**Comment by weddingdj** [comment]
I just tested Cardboard Camera again and it creates a panorama photo, not a photosphere with equirectangular projection. That's why the resolution is not 2:1. 

https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.youtube.com/watch%3Fv%3DNPs3eIiWRaw&ved=2ahUKEwj75MOvuuThAhVPgK0KHd--D_UQjjgwDnoECAIQAQ&usg=AOvVaw2JyVnGQtCwlF87GG0ctuND&cshid=1555962133303

**Comment by konstantinosko** [comment]
I just used the panorama 360 app and my picture has the resolution of 7206x1008. At the top of the app there is an HD "turn on" button and once I click on it, asks me to pay 10 euro to upgrade to the pro version.
Will that option make my photos 2:1 aspect ratio?

**Comment by weddingdj** [comment]
HD does not sound like it enables you to take 2:1 photos. Could you give me a link which app you are using? I created my photospheres with a 360 camera, eg. Gear 360.

**Comment by weddingdj** [comment]
You can also ask the app makers if they support 2:1 equirectangular photos.

**Comment by konstantinosko** [comment]
Am using the panorama 360 from google play store and I am trying to take the photos with my phone's camera.. That's why I didn't get the right aspect ratio?

**Comment by weddingdj** [comment]
Yes, it could be that the app is not supporing 360 equirectangular photos. Here are some examples: https://www.flickr.com/groups/equirectangular/

**Comment by konstantinosko** [comment]
Do you have any app to suggest for my phone "Huawei P20 pro" or should I buy the "gear360" cam?

**Comment by weddingdj** [comment]
I don't know any app currently which supports creating a photosphere. It worked with my previous camera app on android, but this function is not there anymore (at least on my Samsung S7). I would not suggest getting the Gear 360 camera, I think the Ricoh Theta S is better. But it depends on the budget as well.

**Comment by konstantinosko** [comment]
Ok and if I proceed to buy the (Ricoh Theta S) I can take photo-sphere with 2:1 aspect ratio?

**Comment by weddingdj** [comment]
Yes.

**Comment by konstantinosko** [comment]
Ok then, and which apk should I use to take the photos?

**Comment by weddingdj** [comment]
The camera takes the photos which are stored on the camera.
