### ISSUE TITLE
Space Settings 

### ISSUE THREAD

**Issue by g3rman42** [IdeaSpaceVR/IdeaSpace#70]
In version 1.2 under "Settings -> Space", when setting the front page display to "Blank Page" this works correctly. However when selecting a specific space to land on the directory parsing seems to not work correctly and an error is displayed.
Screenshot is attached.
![Screenshot_2](https://user-images.githubusercontent.com/16504943/60986513-3cb26900-a305-11e9-9242-901056bd4ed6.png)

**Comment by weddingdj** [comment]
Did you download v1.2 directly from Github? It is not officially released yet, but I will have a look at this issue.

**Comment by weddingdj** [comment]
I reproduced the bug, thanks for filing!

**Comment by g3rman42** [comment]
Confirmed fixed, thanks!

**Comment by g3rman42** [comment]
Looks like it may not be entirely fixed. If I am logged in and I access "www.stclaresalumni.org/vr/login" it shows the admin page for a couple of seconds and then proceeds to load the selected default VR space.

**Comment by weddingdj** [comment]
Why would you want to access the login page (www.stclaresalumni.org/vr/login) when you are logged in?

**Comment by weddingdj** [comment]
It is indeed showing the admin page for a moment then redirects to the VR space. This is expected behavior, because by calling login I check if the user is logged in, so it would show the admin page, but since we are at the root of the installation it shows the selected VR space.

**Comment by g3rman42** [comment]
Sorry, my understanding was that in order to access the admin portal you have to access www.url.com/login.
When I try to access "https://www.stclaresalumni.org/vr/admin" I get an error of:

The requested URL /admin was not found on this server.

Notice that Ideaspace is installed in a subdirectory but tries to call the admin page at the root of the site, where it obviously does not exist.

**Comment by weddingdj** [comment]
I test installed it in a sub-directory as well. The behavior is as follows:

Not logged in:
If you access https://www.stclaresalumni.org/vr/admin or https://www.stclaresalumni.org/vr/login it redirects to login. I tested it with your URL.

Logged in:
If you access https://www.stclaresalumni.org/vr/admin you land on the dashboard. If you access https://www.stclaresalumni.org/vr/login you are redirected to https://www.stclaresalumni.org/vr/ (your VR space). I tested it with my install.

Let me know.

**Comment by g3rman42** [comment]
Found the problem. The difference is the final "/"

https://www.stclaresalumni.org/vr/admin - works
https://www.stclaresalumni.org/vr/admin/ - redirects to incorrect directory

Looks like Firefox adds the final / by default

**Comment by weddingdj** [comment]
I just had a look in Firefox and both /admin and /admin/ redirect to /login (not logged in user). Same behavior when you are logged in.
