### ISSUE TITLE
Security issue: Escape ldap with ldap_escape

### ISSUE THREAD

**Issue by mortezasaki** [IdeaSpaceVR/IdeaSpace#72]
Dear dev,
Per [RFC 4514](http://tools.ietf.org/html/rfc4514#section-2.4) ,you must escaping leading/trailing spaces in DN strings
Since PHP 5.6 the function [ldap_escape ](http://php.net/manual/en/function.ldap-escape.php)allow escape input contextually for FILTER and DN.

https://ldap.com/2018/05/04/understanding-and-defending-against-ldap-injection-attacks/

**Comment by weddingdj** [comment]
Thank you, this issue is already adressed.
